# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qe8Fn1dLxqvgFV369Qba_ZXv4w3o5rwX
"""

!pip install tensorflow==2.12.0
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = keras.datasets.mnist.load_data()

model_cnn = keras.Sequential()
model_cnn.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)))
model_cnn.add(layers.MaxPooling2D(2,2))
model_cnn.add(layers.Conv2D(64, (3,3), activation = 'relu'))
model_cnn.add(layers.MaxPooling2D(2,2))
model_cnn.add(layers.Conv2D(64, (3,3), activation='relu'))
model_cnn.add(layers.Flatten())
model_cnn.add(layers.Dense(64, activation = 'relu'))
model_cnn.add(layers.Dense(10, activation = 'softmax'))

train_images_cnn = train_images.reshape(60000, 28, 28, 1)
train_images_cnn = train_images_cnn.astype('float32') / 255

test_images_cnn = test_images.reshape(10000, 28, 28, 1)
test_images_cnn = test_images_cnn.astype('float32') / 255

train_labels_cnn = to_categorical(train_labels)
test_labels_cnn = to_categorical(test_labels)

model_cnn.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

model_cnn.fit(train_images_cnn, train_labels_cnn, epochs = 5, batch_size = 60)

model_cnn.save('handwriting.keras')